### ISSUE TITLE
ERROR: query REMARK  not found

### ISSUE THREAD

**Issue by YiningWang2** [stivalaa/cuda_satabsearch#1]
Hello, when I use this to search substructure, I met this error. Is there any advice to solve this?
![屏幕快照 2022-08-24 下午2 16 24](https://user-images.githubusercontent.com/25558295/186344731-e01a5251-515e-46e9-8cc5-f7d07a904631.png)

**Comment by stivalaa** [comment]
From the filenames and the error message it looks like you are not providing the correct input formats. I'm guessing from the ".pdb" suffix and error that "REMARK" is not found, that your database and query are PDB files. But the program does not deal directly with PDB files, but rather protein "tableaux". These describe protein structures by their secondary structures, as described in the publication cited in the README file  and the citations therein.

The tableaux are created from PDB files with scripts that are provided in the scripts directory, specifically buildtableauxdb.py and convdb2.py as described in the README (which also shows examples), and pytableaucreate.py to create individual query tableaux. Detail documentation in provided in the scripts.

**Comment by YiningWang2** [comment]
I see, thanks so much. I changed database into  "tableaux" but forgot the query. As you mentioned above, I used pytableaucreate.py to generate the the protein "tableaux". But this occurred. I want to know whether this is because of the wrong way i uesd or my input query is not suitable.
![屏幕快照 2022-08-25 下午2 38 03](https://user-images.githubusercontent.com/25558295/186592867-beab6084-a587-41cc-9680-ec3a0b5cebf3.png)

**Comment by stivalaa** [comment]
It is trying to run DSSP to define secondary structures (because the default of using HELIX and SHEET cards in the PDB failed as there weren't any) but the DSSP executable (dsspcmbi) is not found. So you need to have DSSP (Kabsch & Sander, 1983) available on your system and the dsspcmbi executable in the PATH so the script can run it.

As per the README for the paper I ran it with the " -t dssp -3 -5" options to use DSSP (although the default is to use HELIX and SHEET records from the PDB file, I always actually used it with DSSP to get consistent definitions and handle PDB structures that do not have HELIX and SHEET records).

**Comment by stivalaa** [comment]
closed?

**Comment by YiningWang2** [comment]
Hello, I installed DSSP followed this repo, but still get this error. Could you please give me a detailed tutorial on how to get the sub-protein structure with a query pdb file and adatabase folder with many pdb files.
<img width="944" alt="截屏2022-09-08 下午9 50 56" src="https://user-images.githubusercontent.com/25558295/189139720-99637c64-7ee5-4d38-8831-ba94771625ad.png">

**Comment by stivalaa** [comment]
It looks like you have a newer version of DSSP that is different from the old one from when I wrote this code. I've never heard of 'mkdssp',I run DSSP like this (with DSSP code from some time around 2007):

      [stivala@icslogin01 proorigami]$ dssp/dsspcmbi 
      COPYRIGHT
        W. Kabsch, C. Sander and MPI-MF, 1983, 1985, 1988, 1994 1995
        CMBI version by Elmar.Krieger@cmbi.ru.nl / April 4, 2006
      USAGE
        dssp/dsspcmbi [Options] PDB_File DSSP_File -> Read PDB_File and write DSSP_File
        dssp/dsspcmbi [Options] -- dssp_file       -> Read from stdin and write DSSP_File
        dssp/dsspcmbi -h                           -> Display this help screen
      OPTIONS
        -na   Disables the calculation of accessible surface.
        -c    Classic (old) format.
        -w    Wide 2002 format (for future use,not the current standard).
        -v    Verbose.
        --    Read from standard input.
      
        -h -? Prints a help message.
        -V    Prints version, as in first line of the output.
      ADDITIONAL OPTIONS CONTRIBUTED BY DSSP USERS
        By Emmanuel.Courcelle@toulouse.inra.fr
        -ssa  Adds information about disulfide bonds to output file
        -x    Renames residues with incomplete sidechains to 'X'
        -alt2 Keeps an additional AltLoc indicator at the line ends

So you could try changing the code in ptsecstruct.py (read_secstruct_from_dssp()) to run mkdssp with the appropriate options (looks like "mkdssp -i filename.pdb -o stdout" instead of "dsspcmbi filename.pdb") - but maybe the output format is not the same anymore either, so I have no idea if this will still work.

Or you could try the "-t stride" option to use STRIDE (Frishman and Argos 1995), http://webclu.bio.wzw.tum.de/stride/ instead of DSSP, but again I used the version from 2007 so it also might have changed.

        [stivala@icslogin01 spike]$ stride       
        
        You must specify input file 
        
        Action: secondary structure assignment
        Usage: stride [Options] InputFile [ > file ]
        Options:  
          -fFile      Output file
          -mFile      MolScript file
          -o          Report secondary structure summary Only
          -h          Report Hydrogen bonds
          -rId1Id2..  Read only chains Id1, Id2 ...
          -cId1Id2..  Process only Chains Id1, Id2 ...
          -q[File]    Generate SeQuence file in FASTA format and die
        
        Options are position  and case insensitive
        
        [stivala@icslogin01 spike]$ python2 ~/proorigami/pro-origami/pytableaucreate.py -t stride -b -f  ~/pconpy/tests/pdb_files/1ubq.pdb
           1UBQ    6
        e  
        OT e  
        LE RT xa 
        RT LE RT e  
        LE RT LE OT e  
        PE RT LE OT PE e  
         0.000 
         4.249  0.000 
        11.944 10.374  1.000 
        11.495 13.762 11.857  0.000 
        15.612 18.778 17.210  6.506  0.000 
         8.878 11.115 12.271  4.567  9.961  0.000 
        
        [stivala@icslogin01 spike]$ python2 ~/proorigami/pro-origami/pytableaucreate.py -t stride -b -f 6CRZ.pdb > 6CRZ.query  2> warnings6CRZ.err
        [stivala@icslogin01 spike]$ head 6CRZ.query 
           6CRZ  230
        e  
        RD e  
        OS OS e  
        RT LS RD e  
        LE RT LS OS e  
        RT LE RT PE OT e  
        LE OT RD RT PE OT e  
        RD PE LS LE RT PE OT e  
        OS OT PD RD LS RT LE RT e  
        [stivala@icslogin01 spike]$ 
        [stivala@icslogin01 spike]$ head warnings6CRZ.err 
        /home/stivala/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:91: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 26692.
          PDBConstructionWarning)
        /home/stivala/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:91: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 26960.
          PDBConstructionWarning)
        /home/stivala/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:91: PDBConstructionWarning: WARNING: Chain C is discontinuous at line 27242.
          PDBConstructionWarning)
        WARNING: distance 100.693625 at (49,29) truncated to 99.9 for fortran format
        WARNING: distance 103.990702 at (49,30) truncated to 99.9 for fortran format
        WARNING: distance 101.422918 at (53,24) truncated to 99.9 for fortran format
        WARNING: distance 101.811399 at (53,29) truncated to 99.9 for fortran format
        [stivala@icslogin01 spike]$

**Comment by stivalaa** [comment]
Example query building and running (on small test database in github):
        
        [stivala@icslogin01 spike]$ echo "/home/stivala/public_github/cuda_satabsearch/old/nvcc_src_cuda5/tableauxdistmatrixdb.small.ascii" > ubiquiin.query
        [stivala@icslogin01 spike]$ echo "T T F" >> ubiquiin.query 
        [stivala@icslogin01 spike]$ python2 ~/proorigami/pro-origami/pytableaucreate.py -3 -5 -t stride -b -f  ~/pconpy/tests/pdb_files/1ubq.pdb >> ubiquiin.query 
        [stivala@icslogin01 spike]$ 
        [stivala@icslogin01 spike]$ cat ubiquiin.query  
        /home/stivala/public_github/cuda_satabsearch/old/nvcc_src_cuda5/tableauxdistmatrixdb.small.ascii
        T T F
           1UBQ    8
        e  
        OT e  
        LE RT xa 
        PD OS RD xg 
        RT LE RT LS e  
        LE RT LE LS OT e  
        RT LS LS RD PE OS xg 
        PE RT LE RD OT PE RT e  
         0.000 
         4.249  0.000 
        11.944 10.374  1.000 
        17.953 17.702  9.833  3.000 
        11.495 13.762 11.857 10.583  0.000 
        15.612 18.778 17.210 15.380  6.506  0.000 
        14.617 17.265 16.292 20.111 13.272 11.643  3.000 
         8.878 11.115 12.271 12.482  4.567  9.961 15.699  0.000 
        [stivala@icslogin01 spike]$ 
        [stivala@icslogin01 spike]$ ~/cuda_satabsearch/nvcc_src_current/cudaSaTabsearch  -c < ubiquiin.query  > ubiquitin_results_cpu.out
        MAXDIM = 111 (edit in saparams.h and recompile to change)
        Read 1 query structures
        Loading database...
        Loaded 586 db entries (0 order > 96) in 19.839001 ms
        maxstart = 128
        Executing simulated annealing tableaux match kernel on host for query 1UBQ...
        running on host
        host execution time 665.526978 ms
        11.270467 million iterations/sec
        [stivala@icslogin01 spike]$ 
        [stivala@icslogin01 spike]$ head ubiquitin_results_cpu.out 
        # cudaSaTabsearch LTYPE = T LORDER = T LSOLN = F
        # QUERY ID = 1UBQ    
        # DBFILE = /home/stivala/public_github/cuda_satabsearch/old/nvcc_src_cuda5/tableauxdistmatrixdb.small.ascii
        d1kcul1  6 0.6 -1.27278 0.943444
        d1rroa_  4 0.421053 -1.27278 0.943444
        d1weva_  2 0.307692 -1.27278 0.943444
        d2pq3a1  4 0.533333 -1.27278 0.943444
        d1nldl1  8 0.842105 -1.27278 0.943444
        d1lfwa2  5 0.434783 -1.27278 0.943444
        d1lfwa1  7 0.466667 -1.27278 0.943444
        [stivala@icslogin01 spike]$ 
        [stivala@icslogin01 spike]$ srun -p gpu --mem=8G --time=1:0:0 --pty  bash -i
        [stivala@icsnode05 spike]$ ~/cuda_satabsearch/nvcc_src_current/cudaSaTabsearch   < ubiquiin.query > ubiquitin_results_gpu.out 
        MAXDIM = 111 (edit in saparams.h and recompile to change)
        Read 1 query structures
        Loading database...
        Loaded 586 db entries (0 order > 96) in 23.226999 ms
        found 1 CUDA devices
        found modern architecture (compute capability 8.0) device 0: NVIDIA A100-PCIE-40GB
        using device 0: NVIDIA A100-PCIE-40GB
        totalGlobalMem              = 39.5861 GB
        sharedMemPerBlock           = 48 KB
        warpSize                    = 32
        maxThreadsPerBlock          = 1024
        clockRate                   = 1410 MHz
        totalConstMem               = 64 KB
        multiProcessorCount         = 108
        maxThreadsPerMultiProcessor = 2048
        sharedMeMPerMultiprocessor  = 32 KB
        maxBlocksPerMultiProcessor  = 0
        maxstart = 128
        Execution configuration: Grid = (128,1,1) Block = (128,1,1)
        using shared memory for small db structs: YES
        Copying database to device...
        Initialized device RNG with 16384 states (768 KB) in 2.842000 ms
        d_tableaux.pitch == 512 xsize == 96 ysize == 96
        d_distmatrices.pitch == 512 xsize == 384 ysize == 96
        srcPtr.pitch == 96
        distmatrices srcPtr.pitch == 384
        Copied 586 entries to GPU in 22.931000 ms
        XXX c_qn_addr = 0x7fdd815f8500 , qn = 8
        Copying query to constant memory took 0.054000 ms
        Executing simulated annealing tableaux match kernel ( shared memory) on GPU for qid 1UBQ...
        xxx_qn=8
        GPU execution time 5.931000 ms
        1264.677071 million iterations/sec
        [stivala@icsnode05 spike]$ 
        [stivala@icsnode05 spike]$ exit
        [stivala@icslogin01 spike]$ head ubiquitin_results_gpu.out 
        # cudaSaTabsearch LTYPE = T LORDER = T LSOLN = F
        # QUERY ID = 1UBQ    
        # DBFILE = /home/stivala/public_github/cuda_satabsearch/old/nvcc_src_cuda5/tableauxdistmatrixdb.small.ascii
        d1kcul1  11 1.1 0.903563 0.161558
        d1rroa_  5 0.526316 -1.27278 0.943444
        d1weva_  2 0.307692 -1.27278 0.943444
        d2pq3a1  3 0.4 -1.27278 0.943444
        d1nldl1  11 1.15789 0.903563 0.161558
        d1lfwa2  9 0.782609 -1.27278 0.943444
        d1lfwa1  9 0.6 -1.27278 0.943444
        [stivala@icslogin01 spike]$ 
        [stivala@icslogin01 spike]$ cat ubiquitin_results_gpu.out  | grep -v '^#' | sort -k 2,2nr |head
        d1c3ta_  42 5.25 9.60895 2.49513e-06
        d2faza1  41 5.46667 9.60895 2.49513e-06
        d1uela_  36 4.5 7.4326 4.06742e-05
        d3seba2  25 2.77778 3.07991 0.0107511
        d1qnga_  24 2.28571 3.07991 0.0107511
        d1xo7a_  24 2.4 3.07991 0.0107511
        d1ahsa_  20 2 3.07991 0.0107511
        d1ihga2  19 1.80952 0.903563 0.161558
        d1rm6c2  19 2.23529 3.07991 0.0107511
        d1tlya_  19 1.58333 0.903563 0.161558
        [stivala@icslogin01 spike]$ 

shows that the top-scoring structures (and with small p-values) are ubiquitin-like e.g d1c3ta_

**Comment by stivalaa** [comment]
This shows how to build the database. Starting with the ASTRAL SCOP 40% sequence identity subset (v2.07) downloaded today from https://scop.berkeley.edu/astral/pdbstyle/ver=2.08 which when uncompressed is a hierarchy of 14 323 PDB files (about  4.2GB) , we end up with the 22 MB tableaux + distance matrix db file with 14 297 entries (some have no SSEs so are skipped), in ASCII format, sorted by size, for use with cudaSaTabsearch:

```
  [stivala@icsnode17 astral]$ time python2 ~/cuda_satabsearch/scripts/buildtableauxdb.py -t stride -3 -5 -p none ./pdbstyle-2.07 astral-sel-gs-bib-40-2.07-tableaux.pickle > buildtabldauxdb1.out 2> buildtabldauxdb1.err                        
  
  real    48m9.281s
  user    45m10.867s
  sys     3m4.331s
  [stivala@icsnode17 astral]$ 
  
  /home/stivala/cuda_satabsearch/scripts/buildtableauxdb.py: version is: Revision 3839M, Tue Jun 29 17:03:49 EST 2010
  /home/stivala/cuda_satabsearch/scripts/buildtableauxdb.py: options are: ['-t', 'stride', '-3', '-5', '-p', 'none', './pdbstyle-2.07', 'astral-sel-gs-bib-40-2.07-tableaux.pickle']
  processed 14323 files
  resulting in 14323 db entries
               14297 tableaux
  with 0 duplicate key errors
  writing tableaux db to astral-sel-gs-bib-40-2.07-tableaux.pickle...
  done.
  [stivala@icsnode17 astral]$ 
  [stivala@icsnode17 astral]$ time python2 ~/cuda_satabsearch/scripts/buildtableauxdb.py -t stride -3 -5 -p none -d ./pdbstyle-2.07 astral-sel-gs-bib-40-2.07-distmatrices.pickle > buildtabldauxdb2.out 2> buildtabldauxdb2.err                 
  
  real    30m53.349s
  user    28m40.969s
  sys     2m35.274s
  [stivala@icsnode17 astral]$ 
  [stivala@icsnode17 astral]$ cat buildtabldauxdb2.out 
  /home/stivala/cuda_satabsearch/scripts/buildtableauxdb.py: version is: Revision 3839M, Tue Jun 29 17:03:49 EST 2010
  /home/stivala/cuda_satabsearch/scripts/buildtableauxdb.py: options are: ['-t', 'stride', '-3', '-5', '-p', 'none', '-d', './pdbstyle-2.07', 'astral-sel-gs-bib-40-2.07-distmatrices.pickle']
  processed 14323 files
  resulting in 14323 db entries
               14297 SSE distance matrices
  with 0 duplicate key errors
  writing SSE distance matrix db to astral-sel-gs-bib-40-2.07-distmatrices.pickle...
  done.
  [stivala@icsnode17 astral]$ 
  [stivala@icsnode17 astral]$ time python2 ~/cuda_satabsearch/scripts/convdb2.py -s astral-sel-gs-bib-40-2.07-tableaux.pickle astral-sel-gs-bib-40-2.07-distmatrices.pickle > tableauxdistmatrixdb-sel-gs-bib-40-2.07.sorted.ascii
  loading tableaux...
  loading distance matrices...
  writing ASCII format tableaux+distmatrices...
  sorting database...
  wrote 14297 tableaux+distmatrices for 14297 entries
  
  real    0m15.047s
  user    0m14.934s
  sys     0m1.154s
  [stivala@icsnode17 astral]$ 
 ```

And now we can do a query in this database (I just changed the first line of the query to have the filename of the new database file just created):

```
[stivala@icsnode05 astral]$ cat ubiquitin.query                                
/scratch/stivala/astral/tableauxdistmatrixdb-sel-gs-bib-40-2.07.sorted.ascii   
T T F
   1UBQ    8                                                                   
e
OT e                                                                           
LE RT xa                                                                       
PD OS RD xg
RT LE RT LS e
LE RT LE LS OT e
RT LS LS RD PE OS xg
PE RT LE RD OT PE RT e                                                         
 0.000                                                                         
 4.249  0.000                                                                  
11.944 10.374  1.000
17.953 17.702  9.833  3.000
11.495 13.762 11.857 10.583  0.000                                             
15.612 18.778 17.210 15.380  6.506  0.000                                      
14.617 17.265 16.292 20.111 13.272 11.643  3.000                               
 8.878 11.115 12.271 12.482  4.567  9.961 15.699  0.000                        

stivala@icsnode05 astral]$ ~/cuda_satabsearch/nvcc_src_current/cudaSaTabsearch   < ubiquitin.query > ubiquitin_results_gpu.out                               

MAXDIM = 111 (edit in saparams.h and recompile to change)
Read 1 query structures
Loading database...                                                                                                                                           
Tableau d4c2ma_ order 115 is too large (max is 111)
WARNING: excluded database structure d4c2ma_ as it is too large
Tableau d4g7hd_ order 131 is too large (max is 111)
WARNING: excluded database structure d4g7hd_ as it is too large
WARNING: skipped 2 tableaux of order > 111
Loaded 14295 db entries (4 order > 96) in 774.919983 ms                                                                                                       
found 1 CUDA devices
found modern architecture (compute capability 8.0) device 0: NVIDIA A100-PCIE-40GB                                                                            
using device 0: NVIDIA A100-PCIE-40GB
totalGlobalMem              = 39.5861 GB                                                                                                                      
sharedMemPerBlock           = 48 KB
warpSize                    = 32                                                                                                                              
maxThreadsPerBlock          = 1024
clockRate                   = 1410 MHz                                                                                                                        
totalConstMem               = 64 KB                                                                                                                           
multiProcessorCount         = 108
maxThreadsPerMultiProcessor = 2048                                                                                                                            
sharedMeMPerMultiprocessor  = 32 KB                                                                                                                           
maxBlocksPerMultiProcessor  = 0
maxstart = 128                                                                                                                                                
Execution configuration: Grid = (128,1,1) Block = (128,1,1)
using shared memory for small db structs: YES
Copying database to device...
Initialized device RNG with 16384 states (768 KB) in 2.826000 ms
d_tableaux.pitch == 512 xsize == 96 ysize == 96
d_distmatrices.pitch == 512 xsize == 384 ysize == 96                                                                                                          
srcPtr.pitch == 96                                                                                                                                            
distmatrices srcPtr.pitch == 384                                                                                                                              
Copied 14291 entries to GPU in 96.946999 ms                                                                                                                   
XXX c_qn_addr = 0x7f20df5f8500 , qn = 8
Copying query to constant memory took 0.054000 ms
Executing simulated annealing tableaux match kernel ( shared memory) on GPU for qid 1UBQ...
xxx_qn=8
GPU execution time 96.112999 ms
1903.226431 million iterations/sec
Copying large structure database to device...
d_tableaux.pitch == 512 xsize == 111 ysize == 111
d_distmatrices.pitch == 512 xsize == 444 ysize == 111
srcPtr.pitch == 111
distmatrices srcPtr.pitch == 444
Copied 4 large entries to GPU in 1.330000 ms
XXX c_qn_addr = 0x7f20df341400 , qn = 8
Copying query to constant memory took 0.043000 ms
Executing simulated annealing tableaux match kernel (no shared memory) on GPU for qid 1UBQ...
xxx_qn_noshared=8
GPU (no shared memory) execution time 5.231000 ms
9.787804 million iterations/sec
[stivala@icsnode05 astral]$ 
[stivala@icsnode05 astral]$ cat ubiquitin_results_gpu.out  | grep -v '^#' | sort -k 2,2nr |head
d3m62b_  54 6.75 11.7853 1.53059e-07
d2bwfa_  53 6.625 11.7853 1.53059e-07
d2faza1  52 6.5 11.7853 1.53059e-07
d3a9ja_  52 6.5 11.7853 1.53059e-07
d3zdmc_  51 6.375 11.7853 1.53059e-07
d4eewa_  48 6 11.7853 1.53059e-07
d3kuza1  47 5.22222 9.60895 2.49513e-06
d2wyqa_  46 5.75 9.60895 2.49513e-06
d4icva_  44 5.5 9.60895 2.49513e-06
d1yqba1  42 5.25 9.60895 2.49513e-06

```

**Comment by YiningWang2** [comment]
WoW! I was deeply touched by your detailed answers which are quite helpful for me.  I used the way you said on changing the cmd for mkdssp, but still met an error. 


`(sub) wyn@cnic-ai3:~/Protein/test_Para/cuda_satabsearch$ python ./scripts/pytableaucreate.py ./pdb/T1024-D1.pdb 
WARNING: error with HELIX or SHEET cards in PDB: dssp will be used instead
WARNING: No helices or strands found in T1024-D1: skipping`

It seems that dssp worked well. When i used dssp only, it can generate the secondary structure.
`(sub) wyn@cnic-ai3:~/Protein/test_Para/cuda_satabsearch$ mkdssp -i pdb/T1024-D1.pdb                         
`
<img width="930" alt="截屏2022-09-10 上午11 40 26" src="https://user-images.githubusercontent.com/25558295/189467279-3aa96eda-c53d-4a49-87f9-c294f827360f.png">

So, I am wondering if the error mentioned before is because of my input pdb file. Can you show me your pdb file to let me have a try?

And another important thing i want to say is that today is our Mid-Autumn Festival in China, May you a good day.

**Comment by stivalaa** [comment]
I'm using ubiquitin structure 1UBI as my usual example for testing (https://files.rcsb.org/download/1UBI.pdb). I just installed the latest version of DSSP in Ubuntu Linux (DSSP 4.0.4). But it looks different again from the one you have:

```
alex@alex-Inspiron-15-3567:~/Documents/public_code/cuda_satabsearch$ mkdssp --version
mkdssp version 4.0.4

alex@alex-Inspiron-15-3567:~/Documents/public_code/cuda_satabsearch$ mkdssp -h
mkdssp [options] input-file [output-file]:
  --dict arg            Dictionary file containing restraints for residues in 
                        this specific target, can be specified multiple times.
  --output-format arg   Output format, can be either 'dssp' for classic DSSP or
                        'mmcif' for annotated mmCIF. The default is chosen 
                        based on the extension of the output file, if any.
  --min-pp-stretch arg  Minimal number of residues having PSI/PHI in range for 
                        a PP helix, default is 3
  --write-other         If set, write the type OTHER for loops, default is to 
                        leave this out
  -h [ --help ]         Display help message
  --version             Print version
  -v [ --verbose ]      verbose output
```

I modified the scripts (in branch "dssp4" in this repository, not merged into master yet) to use this version (by calling mkdssp instead of dsspcmbi) when you use "-t dssp4" instead of "-t dssp" - and it seems to work, the dssp 4 option "--output-format=dssp" gives the same format as the old dssp, when I compare the tableaux and distance matrices to the old ones, they only have slight differences due to presumably the slight differences in definitions in the newer DSSP version (also getting some warnings about sef-bridges that the old version did not have):

```
alex@alex-Inspiron-15-3567:~/Documents/public_code/cuda_satabsearch$ python2 scripts/pytableaucreate.py -3 -5 -t dssp4 -f -b  ~/Downloads/1ubi.pdb 
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_5
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_1
WARNING: ignoring self-bridge STRAND_A_5
   1UBI    8
e  
OT e  
LE RT xa 
PD OS RD xg 
RT LE RT LS e  
LE RD LE LS OT e  
RT LS LS RD PE OS xg 
PE RT LE RD OT PE RT e  
 0.000 
 4.501  0.000 
11.662 10.386  1.000 
16.932 17.644  9.779  3.000 
10.588 13.738 11.815 10.527  0.000 
15.025 18.692 17.143 15.341  6.466  0.000 
15.298 17.276 16.276 20.075 13.264 11.610  3.000 
 7.549 11.072 12.248 12.446  4.583  9.903 15.689  0.000 

```
It can also be helpful to add the -v (verbose) option to pytableaucreate.py (and other) scripts to see what is going on in more detail.

Thank you for your kind words. Happy Mid-Autumn Festival!

**Comment by YiningWang2** [comment]
Hi, after i installed dssp4.0 the above problem solved, thanks so much. But I met another problem when i  built the database, do you know why this occurred?
`(subsearch) yining@ai-dgx02:~/tools/cuda_satabsearch$ time python2 scripts/buildtableauxdb.py -t dssp4 -3 -5 -p none ./demo/pdbstyle-2.08-small astral-sel-gs-bib-40-2.08-small-tableaux.pickle > buildtabldauxdb1-small.out 2> buildtabldauxdb1-small.err
`
`(subsearch) yining@ai-dgx02:~/tools/cuda_satabsearch$ cat buildtabldauxdb1-small.err
processing d12asa_.ent
Error parsing PDB at line 13
Error trying to load file "./demo/pdbstyle-2.08-small/2a/d12asa_.ent"
Expected record CRYST1 but found ATOM  
WARNING: No helices or strands found in D12ASA_: skipping
processing d1a04a1.ent
Error parsing PDB at line 13
Error trying to load file "./demo/pdbstyle-2.08-small/a0/d1a04a1.ent"
Expected record CRYST1 but found ATOM  
WARNING: No helices or strands found in D1A04A1: skipping
processing d1a04a2.ent
Error parsing PDB at line 13
Error trying to load file "./demo/pdbstyle-2.08-small/a0/d1a04a2.ent"
Expected record CRYST1 but found ATOM  
WARNING: No helices or strands found in D1A04A2: skipping
`

**Comment by nnnwyn** [comment]
I solved the above problem by adding a CRYST1 line. When i generate SSE distance matrices, 0 matrices was generated. Was it ok?

`(subsearch) yining@ai-dgx02:/nfs_baoding/wangyining/tools/cuda_satabsearch$ time python2 ./scripts/buildtableauxdb.py -t stride -3 -5 -p none -d ./pdbstyle-2.08-small astral-sel-gs-bib-40-2.08—small-distmatrices.pickle > buildtabldauxdb-small2.out 2> buildtabldauxdb2-small.err

real	0m0.277s
user	0m1.924s
sys	0m5.613s`
`
(subsearch) yining@ai-dgx02:/nfs_baoding/wangyining/tools/cuda_satabsearch$ cat buildtabldauxdb2-small.err
(subsearch) yining@ai-dgx02:/nfs_baoding/wangyining/tools/cuda_satabsearch$ cat buildtabldauxdb2-small.out
./scripts/buildtableauxdb.py: version is: Revision 3839M, Tue Jun 29 17:03:49 EST 2010
./scripts/buildtableauxdb.py: options are: ['-t', 'stride', '-3', '-5', '-p', 'none', '-d', './demo/pdbstyle-2.08-small', 'astral-sel-gs-bib-40-2.08-small-distmatrices.pickle']
processed 1 files
resulting in 1 db entries
             0 SSE distance matrices
with 0 duplicate key errors
writing SSE distance matrix db to astral-sel-gs-bib-40-2.08-small-distmatrices.pickle...
done.
`

**Comment by nnnwyn** [comment]
The same way i built buildtabldauxdb1, i get 42 db entries.
`(subsearch) yining@ai-dgx02:/nfs_baoding/wangyining/tools/cuda_satabsearch$ cat buildtabldauxdb1-small.out
scripts/buildtableauxdb.py: version is: Revision 3839M, Tue Jun 29 17:03:49 EST 2010
scripts/buildtableauxdb.py: options are: ['-t', 'dssp4', '-3', '-5', '-p', 'none', './demo/pdbstyle-2.08-small', 'astral-sel-gs-bib-40-2.08-small-tableaux.pickle']
processed 42 files
resulting in 42 db entries
             42 tableaux
with 0 duplicate key errors
writing tableaux db to astral-sel-gs-bib-40-2.08-small-tableaux.pickle...
done.
`

**Comment by nnnwyn** [comment]
Without SSE matix, this error comes.

`(subsearch) yining@ai-dgx02:/nfs_baoding/wangyining/tools/cuda_satabsearch$ time python2 ./scripts/convdb2.py -s astral-sel-gs-bib-40-2.08-small-tableaux.pickle astral-sel-gs-bib-40-2.08-small-distmatrices.pickle > tableauxdistmatrixdb-sel-gs-bib-40-2.08-small.sorted.ascii
loading tableaux...
loading distance matrices...
writing ASCII format tableaux+distmatrices...
sorting database...
ERROR: no distance matrix for id d5aiea1 - skipped
ERROR: no distance matrix for id d1aqta1 - skipped
ERROR: no distance matrix for id d2aqfa2 - skipped
ERROR: no distance matrix for id d1aisb1 - skipped
ERROR: no distance matrix for id d1aiwa_ - skipped
ERROR: no distance matrix for id d1aisb2 - skipped
ERROR: no distance matrix for id d2ab4a1 - skipped
ERROR: no distance matrix for id d1aisa1 - skipped
ERROR: no distance matrix for id d1abva_ - skipped
ERROR: no distance matrix for id d1abaa_ - skipped
ERROR: no distance matrix for id d4aiea2 - skipped
ERROR: no distance matrix for id d3abfa_ - skipped
ERROR: no distance matrix for id d2aiba_ - skipped
ERROR: no distance matrix for id d1aqea_ - skipped
ERROR: no distance matrix for id d1aqza_ - skipped
ERROR: no distance matrix for id d1aqta2 - skipped
ERROR: no distance matrix for id d4aiha_ - skipped
ERROR: no distance matrix for id d5abra_ - skipped
ERROR: no distance matrix for id d1aqma1 - skipped
ERROR: no distance matrix for id d1aqca_ - skipped
ERROR: no distance matrix for id d6aqga1 - skipped
ERROR: no distance matrix for id d3abza3 - skipped
ERROR: no distance matrix for id d4aiva_ - skipped
ERROR: no distance matrix for id d3aixa1 - skipped
ERROR: no distance matrix for id d1ab8a_ - skipped
ERROR: no distance matrix for id d4aqla1 - skipped
ERROR: no distance matrix for id d3abza2 - skipped
ERROR: no distance matrix for id d2aqma_ - skipped
ERROR: no distance matrix for id d4aiaa1 - skipped
ERROR: no distance matrix for id d3aiaa1 - skipped
ERROR: no distance matrix for id d2aiqa_ - skipped
ERROR: no distance matrix for id d2ab0a1 - skipped
ERROR: no distance matrix for id d2ab4a2 - skipped
ERROR: no distance matrix for id d3ai3a_ - skipped
ERROR: no distance matrix for id d2abwa1 - skipped
Traceback (most recent call last):
  File "./scripts/convdb2.py", line 235, in <module>
    main()
  File "./scripts/convdb2.py", line 197, in main
    distmatrix = distmatrixdb[pdbid][tabnum]
IndexError: list index out of range

real	0m0.285s
user	0m1.589s
sys	0m4.577s
`

**Comment by YiningWang2** [comment]
Hi,  i solved the above problem by adding 1 CRYST1 line.  I can do the search successfully now. This issue can be closed i think. Again, I would like to express my warm thanks to you! 

Best wishes,
Nicky

**Comment by stivalaa** [comment]
Those ASTRAL files don't have CRYST1 (or ORIGIN, etc.) records, only HEADER, REMARK, and ATOM (etc.) records. It seems technically this is 'wrong' according to the PDB file format standard (although lots of programs or databases produce PDB files like this), but it worked fine with older version of DSSP, but not DSSP 4:

https://github.com/PDB-REDO/dssp/issues/1
